import './blog.css'
import Rectangle from 'react-rectangle';
import blogcontent from './blogcontent';
import { Link } from 'react-router-dom';

function Blog() {
  return(
    <div className="blog">
      <div className="column aboutinfo">
        <h1>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut posuere magna, quis aliquet ante. Maecenas sit amet sollicitudin urna, ut gravida turpis. Fusce tempus euismod nibh, non luctus turpis interdum eget. Aenean sed lacus tincidunt, feugiat lorem ac, aliquet urna. Quisque in varius nunc. Curabitur non finibus justo. Pellentesque venenatis sollicitudin mollis. Sed vel libero vitae lorem volutpat viverra. Vestibulum id consequat dui. Sed sed rutrum massa.
          Fusce feugiat dignissim est. Duis molestie augue a metus vehicula fringilla. Curabitur vulputate dui nec rhoncus tempus. Mauris blandit eget eros at dictum. Curabitur sollicitudin suscipit nisi, in lacinia eros dapibus a. Duis facilisis ex nec ultrices tempus. Vivamus sed urna arcu. Sed egestas tempor finibus. Ut condimentum rutrum mauris at malesuada. Morbi non ex varius, imperdiet dolor rhoncus, porttitor velit. Mauris lectus lorem, rhoncus vitae enim quis, euismod molestie lacus. Quisque nulla tortor, rhoncus a lacus nec, pretium fringilla neque.
          Maecenas luctus, eros eu finibus luctus, arcu enim cursus lectus, at pretium erat velit at turpis. Morbi sed felis neque. Quisque id vestibulum enim. Morbi interdum euismod nisl iaculis finibus. Etiam porttitor rutrum neque, et molestie enim venenatis vitae. Pellentesque sed tortor quis augue mollis pharetra id sed turpis. Nulla facilisi. Nullam efficitur lorem vitae ipsum viverra ornare. Quisque odio nunc, commodo sed consequat ac, pellentesque ac nibh. Sed scelerisque sed massa sed lobortis. Phasellus scelerisque tincidunt hendrerit. Sed nec dolor quis arcu congue lobortis non eu tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ornare ullamcorper sapien, id consequat elit sollicitudin et. Donec faucibus enim nec nulla tristique, ac volutpat orci condimentum.
          Duis porta, felis ut volutpat suscipit, ligula odio feugiat felis, eu eleifend sapien est porta magna. Suspendisse non orci eu quam viverra dignissim eu in risus. Duis a imperdiet erat. Vestibulum in lacus dolor. Pellentesque vitae scelerisque tortor. Pellentesque at arcu ullamcorper, scelerisque quam vel, elementum massa. Vestibulum sit amet pulvinar ex. Praesent non vulputate odio. Vestibulum venenatis diam a felis ultricies tincidunt. Nunc ornare, ipsum vel tincidunt tempus, ligula eros pellentesque purus, ac volutpat felis nisl blandit ex. Nullam ullamcorper mauris a est luctus, id varius quam euismod. Proin dignissim massa vel risus pulvinar suscipit. In tempor dui in quam sagittis, vitae molestie quam accumsan. Curabitur quis odio et orci cursus condimentum. Nulla nisi nisl, aliquam ut interdum vel, bibendum nec libero. Suspendisse potenti.
          Quisque sollicitudin, ante non fringilla vestibulum, tortor massa placerat nibh, at ornare lacus nunc vitae neque. Maecenas pharetra, justo interdum eleifend cursus, lacus leo egestas metus, ut vestibulum neque orci eget eros. Ut cursus lectus nec enim consectetur, vel suscipit nisi aliquam. Fusce scelerisque magna enim. Sed ut gravida neque. Duis facilisis vitae nibh vitae imperdiet. Curabitur ut ligula nibh. In vehicula ligula id tortor posuere tempus. Mauris semper erat id ante auctor mattis.  
        </h1>
      </div>
      <div className="column blogcontent">
        <p className="postitle">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut posuere magna, quis aliquet ante. Maecenas sit amet sollicitudin urna, ut gravida turpis. Fusce tempus euismod nibh, non luctus turpis interdum eget. Aenean sed lacus tincidunt, feugiat lorem ac, aliquet urna. Quisque in varius nunc. Curabitur non finibus justo. Pellentesque venenatis sollicitudin mollis. Sed vel libero vitae lorem volutpat viverra. Vestibulum id consequat dui. Sed sed rutrum massa.
          Fusce feugiat dignissim est. Duis molestie augue a metus vehicula fringilla. Curabitur vulputate dui nec rhoncus tempus. Mauris blandit eget eros at dictum. Curabitur sollicitudin suscipit nisi, in lacinia eros dapibus a. Duis facilisis ex nec ultrices tempus. Vivamus sed urna arcu. Sed egestas tempor finibus. Ut condimentum rutrum mauris at malesuada. Morbi non ex varius, imperdiet dolor rhoncus, porttitor velit. Mauris lectus lorem, rhoncus vitae enim quis, euismod molestie lacus. Quisque nulla tortor, rhoncus a lacus nec, pretium fringilla neque.
          Maecenas luctus, eros eu finibus luctus, arcu enim cursus lectus, at pretium erat velit at turpis. Morbi sed felis neque. Quisque id vestibulum enim. Morbi interdum euismod nisl iaculis finibus. Etiam porttitor rutrum neque, et molestie enim venenatis vitae. Pellentesque sed tortor quis augue mollis pharetra id sed turpis. Nulla facilisi. Nullam efficitur lorem vitae ipsum viverra ornare. Quisque odio nunc, commodo sed consequat ac, pellentesque ac nibh. Sed scelerisque sed massa sed lobortis. Phasellus scelerisque tincidunt hendrerit. Sed nec dolor quis arcu congue lobortis non eu tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ornare ullamcorper sapien, id consequat elit sollicitudin et. Donec faucibus enim nec nulla tristique, ac volutpat orci condimentum.
          Duis porta, felis ut volutpat suscipit, ligula odio feugiat felis, eu eleifend sapien est porta magna. Suspendisse non orci eu quam viverra dignissim eu in risus. Duis a imperdiet erat. Vestibulum in lacus dolor. Pellentesque vitae scelerisque tortor. Pellentesque at arcu ullamcorper, scelerisque quam vel, elementum massa. Vestibulum sit amet pulvinar ex. Praesent non vulputate odio. Vestibulum venenatis diam a felis ultricies tincidunt. Nunc ornare, ipsum vel tincidunt tempus, ligula eros pellentesque purus, ac volutpat felis nisl blandit ex. Nullam ullamcorper mauris a est luctus, id varius quam euismod. Proin dignissim massa vel risus pulvinar suscipit. In tempor dui in quam sagittis, vitae molestie quam accumsan. Curabitur quis odio et orci cursus condimentum. Nulla nisi nisl, aliquam ut interdum vel, bibendum nec libero. Suspendisse potenti.
          Quisque sollicitudin, ante non fringilla vestibulum, tortor massa placerat nibh, at ornare lacus nunc vitae neque. Maecenas pharetra, justo interdum eleifend cursus, lacus leo egestas metus, ut vestibulum neque orci eget eros. Ut cursus lectus nec enim consectetur, vel suscipit nisi aliquam. Fusce scelerisque magna enim. Sed ut gravida neque. Duis facilisis vitae nibh vitae imperdiet. Curabitur ut ligula nibh. In vehicula ligula id tortor posuere tempus. Mauris semper erat id ante auctor mattis.  
        </p>
      </div>
    </div>
  )
}

export default Blog;